### ISSUE TITLE
Refine our validation inner-loop

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/try#1120]
Currently our integration tests are our only validation loop. There isn't a playground where we can just test out the end-to-end. We need to put in the infra and update the steps here (https://github.com/dotnet/try/blob/main/Developer-guide.ipynb) to make this easier.

- [ ] Improve Playwright screenshots. Some are currently blank and others are cropped so you can't see the output area.
- [x] Automate command line steps to avoid copy/paste in developer guide.
- [x] Make node site UI more intuitive.

**Comment by ocallesp** [comment]
My proposal is to implement this webpage https://try.dot.net/  to this net project

**Comment by ocallesp** [comment]
Removed
- [ ] Add a launch profile to launch the mock-project server

since launch profiles doesn't provide a way to launch two servers.

I was trying to add a new environment variable then check for it in order to execute an external process to launch the mock server but it is more complicated to manage that other process.

We will keep the developer-guide as the main flow

**Comment by AbhitejJohn** [comment]
Clsoing this out as well. Tracking the remaining work as a separate work item.
