### ISSUE TITLE
"error" in the In-Browser Tutorial 

### ISSUE THREAD

**Issue by HansSchreuders** [dotnet/try#42]
In  the In-Browser Tutorial I  encounter the  following  "error"
Code :
int what = max + 3;
Console.WriteLine($"An example of overflow: {what}");

Error  message: 
(1,12): error CS0103: The name 'max' does not exist in the current context

**Comment by BillWagner** [comment]
@HansSchreuders  It looks like you were at this step:  https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/numbers-in-csharp#step-3

The code you have above should be added to the interactive window, instead of replacing what's there.  Then, you would have:

```csharp
int max = int.MaxValue;
int min = int.MinValue;
Console.WriteLine($"The range of integers is {min} to {max}");
int what = max + 3;
Console.WriteLine($"An example of overflow: {what}");
```

Then, the sample works correctly.

Can you try that, and close this if that works correctly?

**Comment by HansSchreuders** [comment]
Hi Bill, you are right, this resolves the “error”.
Because this is the first case where the lines have to be added to the previous example it might help of this is indicated in the description. Thank you for the quick response.
Thanks Hans

Verstuurd vanaf mijn iPhone

**Comment by BillWagner** [comment]
Thanks @HansSchreuders I will close this then.
