### ISSUE TITLE
Change default dictionary formatter to be IDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by cartermp** [dotnet/try#554]
The following code is required to get the nice formatting in F#:

```fsharp
System.Collections.Generic.Dictionary<string, int>([("zero", 0); ("one", 1); ("two", 2)])
```
![image](https://user-images.githubusercontent.com/6309070/67531776-d6b1dd80-f678-11e9-9e98-a7c7605c8245.png)

If the formatter works with `IDictionary<TKey, TValue>`, then the code can merely be this:

```fsharp
dict [("zero", 0); ("one", 1); ("two", 2)]
```

Currently it falls back to the `IEnumerablt<T>` formatter.
![image](https://user-images.githubusercontent.com/6309070/67531870-2395b400-f679-11e9-8a42-f4b034b6d0d4.png)

This should allow the same formatting to apply to any code that has a result which implements that interface, such as those using immutable collections.

**Comment by brettfo** [comment]
The issue is exactly the opposite.  The F# `dict` function returns an object that implements `IDictionary<TKey, TValue>`, but **not** `IDictionary` explicitly, and since `IDictionary<TKey, TValue>` doesn't implement `IDictionary` (especially odd since `IEnumerable<T>` implements `IEnumerable`), you get the unexpected behavior.  E.g., the incoming collection is matched against the generic `IDictionary<TKey, TValue>` [here](https://github.com/dotnet/try/blob/4bc88564912991cadad36f9b909f2571a736ca52/Microsoft.DotNet.Interactive.Rendering/HtmlFormatter%7BT%7D.cs#L85), but a few lines below the actual values are extracted assuming `IDictionary` (non-generic) [here](https://github.com/dotnet/try/blob/4bc88564912991cadad36f9b909f2571a736ca52/Microsoft.DotNet.Interactive.Rendering/HtmlFormatter%7BT%7D.cs#L112) which doesn't work in the F# case you you instead get the simple `IEnumerable` that `IDictionary<TKey, TValue>` _does_ implement.

From the F# side, the result of `dict` should implement `IDictionary` directly, but there's also the incorrect assumption in this code base that `IDictionary<TKey, TValue>` implies the implementation of `IDictionary`.  It was just a happy accident that `System.Collections.Generic.Dictionary<TKey, TValue>` implements both.
