### ISSUE TITLE
#r is unable to load an assembly that's already on disk

### ISSUE THREAD

**Issue by tparviainen** [dotnet/try#584]
#### Describe the bug
Please provide as much information as you can.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other:

I'm using dotnet-try via Jupyter Lab and the assembly loading from the disk fails, below is the load command:
```
#r "C:\Users\tomip\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll"
```
and the response:

```
Invalid: Command: #r C:\Users\tomip\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll
```

The version of the dotnet-try is preview build 1.0.19530.1.

If I execute the same command in Visual Studio's C# Interactive (64-bit) window it works properly.

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by KevinRansom** [comment]
@tparviainen,

I am afraid this is due to a difference between C# and F# #r syntax.

In C# #r is followed by a directive string which doesn't require escaping on the \ characters.

In F# #r is followed by a string which requires \ to be escaped I'e \\.

However, that is somewhat annoying so instead often we use @ strings, which are similar to directive strings in C#.

So your code would become:
````
#r @"C:\Users\tomip\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll"
````

And that should work fine.

Kevin

**Comment by tparviainen** [comment]
@KevinRansom 

The change you described, once implemented, will it also impact to #load or #r only? What about csx files that are #load'ed to Jupyter and that contain #r directives should those #r directives be with @ or without?

**Comment by mehmetakbulut** [comment]
I'm not certain `@` is the issue here. (which actually makes the import fail under C#)

I see the following using the C# kernel:
`#r "C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll"`
`Invalid: Command: #r C:/Users/Mehmet/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.dll`

However ironically, it does load the DLL, you can refer to the namespace(s) and use included types. One big caveat: completion only works when typing `using` but not for anything else that involves types from the DLL.

.NET Core SDK: 3.0.100
dotnet-try: 1.0.19555.1+ee3dc325df2fb737bc0af13bbdd9927a9360e59a

**Comment by KevinRansom** [comment]
@mehmetakbulut 

fsi and csi are different scripting languages and there exists prior art, that we will require to be compatible with, as to what is valid in #r and #load arguments.

In F# the provided line can be:
1:
````
#r C:\\Users\\tomip\\.nuget\\packages\\newtonsoft.json\\12.0.2\\lib\\netstandard2.0\\Newtonsoft.Json.dll"
````
2:
````
#r @"C:\Users\tomip\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll"
````
3:
````
#r """C:\Users\tomip\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll"""
````
4:
````
C:/Users/tomip/.nuget/packages/newtonsoft.json/12.0.2/lib/netstandard2.0/Newtonsoft.Json.
````


The invalid command in your C# example is a bug in the **C#** #r command handler certainly we expect #r with valid linux path chars to work.  Please raise a separate issue for that to avoid confusion.

In **F#** #r and #load strings both will require escaped strings or @"" that conform to the existing fsi script language.

C# will undoubtedly continue to use directive strings, to conform with the existing csi scripting language.

**Comment by mehmetakbulut** [comment]
@KevinRansom That makes sense. Will create a separate issue.

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/68504019-09cba380-0219-11ea-879c-fce224b04576.png)
