### ISSUE TITLE
Subsequent #r nuget invocations for the same package id do not update the requested version (C#)

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/try#617]
![image](https://user-images.githubusercontent.com/547415/68504476-e2c1a180-0219-11ea-9b5c-b366f89c5dac.png)

**Comment by KevinRansom** [comment]
@jonsequitur, this is by design.  Once an assembly has been loaded we can't really go fetch another one with a different version.  At some point in the future we may well surface a loadcontext in scripting environments, but certainly for now, neither CSI or FSJ really enable that.

In order to specify a load a different version of a dll thats already loaded, will require a Kernel restart.
